export default {
  staff:
    [{id: 0, name: 'wxw', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      {id: 0, name: 'wxw2', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      {id: 0, name: 'wxw3', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      {id: 0, name: 'wxw4', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      {id: 0, name: 'wxw5', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw6', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw2', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw3', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw4', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw5', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw2', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw3', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw4', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw5', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw2', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw3', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw4', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw5', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw2', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw3', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw4', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw5', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw2', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw3', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw4', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw5', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw2', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw3', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw4', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw5', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw2', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw3', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw4', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw5', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw2', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw3', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw4', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw5', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw2', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw3', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw4', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      // {id: 0, name: 'wxw5', personnelStatus: '在职', tel: '', man: '1', remarks: '', isChecked: false},
      ],
  isCheckedAll: false,
  display: 10,
  // 每页条数
  currentPage: 1,
  // 当前页码

}

